wordpress:
    image: vsregistry.intra.inist.fr:5000/bibcnrs:${bibcnrs_version}
    links:
        - db:mysql
    environment:
        http_proxy: ${http_proxy}
        https_proxy: ${https_proxy}
        WORDPRESS_DB_PASSWORD: ${DB_PASSWORD}
        AUTH_KEY: ${AUTH_KEY}
        SECURE_AUTH_KEY: ${SECURE_AUTH_KEY}
        LOGGED_IN_KEY: ${LOGGED_IN_KEY}
        NONCE_KEY: ${NONCE_KEY}
        AUTH_SALT: ${AUTH_SALT}
        SECURE_AUTH_SALT: ${SECURE_AUTH_SALT}
        LOGGED_IN_SALT: ${LOGGED_IN_SALT}
        NONCE_SALT: ${NONCE_SALT}
    restart: always
