version: "3.5"

services:
  wordpress:
    image: vxnexus-registry.intra.inist.fr:8083/bibcnrs/bibcnrs:${bibcnrs_version}
    environment:
        ROBOT_INDEX: ${ROBOT_INDEX}
        http_proxy: ${http_proxy}
        https_proxy: ${https_proxy}
        WORDPRESS_DB_PASSWORD: ${DB_PASSWORD}
        AUTH_KEY: ${AUTH_KEY}
        SECURE_AUTH_KEY: ${SECURE_AUTH_KEY}
        LOGGED_IN_KEY: ${LOGGED_IN_KEY}
        NONCE_KEY: ${NONCE_KEY}
        AUTH_SALT: ${AUTH_SALT}
        SECURE_AUTH_SALT: ${SECURE_AUTH_SALT}
        LOGGED_IN_SALT: ${LOGGED_IN_SALT}
        NONCE_SALT: ${NONCE_SALT}
    volumes:
        - ./wp-content/uploads:/var/www/html/wp-content/uploads
    restart: always
    networks:
      bibfrontend :
      bibbackend :
        aliases: 
          - wordpress

  db:
    image: mariadb:10.0
    environment:
        MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
        PORT: 3305
        TERM: dumb
    volumes:
        - /applis/bibcnrs/home/mariadb:/var/lib/mysql
    restart: always
    networks:
      bibbackend :
        aliases: 
          - mysql
          
networks:
  bibbackend:
    driver: bridge
    name: bibbackend
  bibfrontend:
    driver: bridge
    name: bibfrontend
