data:
  build: ./data
  volumes:
    - /var/lib/mysql

wordpress:
  build: ./wordpress
  ports:
    - 8080:8080
  links:
    - db:mysql
  environment:
    http_proxy: ${http_proxy}
    https_proxy: ${https_proxy}
    WORDPRESS_DB_PASSWORD: ${DB_PASSWORD}
  working_dir: /var/www/html
  volumes:
    - ./wp-content/plugins:/var/www/html/wp-content/plugins
    - ./wp-content/themes:/var/www/html/wp-content/themes
    - ./vendor:/var/www/html/vendor

db:
  image: mariadb:10.0
  environment:
    MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    PORT: 3305
    TERM: dumb
  volumes_from:
    - data

composer:
  image: composer/composer:1.0.0-alpha10
  environment:
    http_proxy: ${http_proxy}
  volumes:
    - $PWD:/app

compass:
  build: ./compass
  volumes:
    - $PWD:/src
  command: compile

wpcli:
  build: ./appstack-wpcli
  links:
    - db:mysql
  volumes_from:
    - wordpress
