data:
  build: ./data
  volumes:
    - /var/lib/mysql

wordpress:
  image: wordpress
  links:
    - db:mysql
  ports:
    - 8080:80
  environment:
    WORDPRESS_DB_PASSWORD: example

db:
  image: mariadb
  environment:
    MYSQL_ROOT_PASSWORD: example
    PORT: 3305
  volumes_from:
    - data

compass:
  image: antonienko/compass-watch
  volumes:
    - $PWD:/src
  command: watch
