data:
  extends:
    file: ./docker-compose.yml
    service: data

wordpress:
  extends:
    file: ./docker-compose.yml
    service: wordpress
  links:
    - db:mysql
  environment:
    WORDPRESS_DB_PASSWORD: example

db:
  extends:
    file: ./docker-compose.yml
    service: db
  environment:
    MYSQL_ROOT_PASSWORD: example
    PORT: 3305
    TERM: dumb
  volumes_from:
    - data
