data:
  extends:
    file: ./docker-compose.yml
    service: data

wordpress:
  extends:
    file: ./docker-compose.yml
    service: wordpress
  restart: always
  links:
    - db:mysql
  environment:
    WORDPRESS_DB_PASSWORD: ${DB_PASSWORD}

db:
  extends:
    file: ./docker-compose.yml
    service: db
  restart: always
  environment:
    MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    PORT: 3305
    TERM: dumb
  volumes_from:
    - data
